name: Run testcases

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run all java testcases
      with: ~/toolchain-fitnesse-plugin
      run: mvn test
